EasyRPG/easyrpg.org

- Rules
- content/player/downloads.html
Do not merge yet, need to change codename and blog url when ready.
> Player 0.4

- content/player/downloads.html
> Update Player download links for version 0.4.1

- content/contribute/artists.html
- content/contribute/programmers.html
- content/editor/downloads.html
- content/player.html
- content/player/downloads.html
- content/robots.txt
- content/tools/downloads.html
- layouts/default.html
- nanoc.yaml
do not merge yet, this will fail without updating the jenkins job anyway.
> Update URLs for server/domain move

- content/player/downloads.html
This will likely not pass the check, because the files are missing yet ;)
> Player/liblcf 0.5.1

- content/player/downloads.html
Enable WinRT port release link
Fix OSX port CI link
*As usual, expect build failures until everything is in place.*
> liblcf/Player 0.5.2

- content/player/downloads.html
(via https://community.easyrpg.org/t/small-fix-for-homebrew-install-suggestion/506)
> Update brew installation command

- content/player/downloads.html
Windows ARM is deprecated, GCW Zero shines again.
Rinne looses a bit of fame :hear_no_evil:
> Update download links for 0.5.4

- content/player/downloads.html
- content/tools/downloads.html
> Player 0.6 release + Add Amiga + Update Windows Tool links

- content/player/downloads.html
- content/player/progress.html
> Player 0.6.1 release

- content/player/downloads.html
> Update Player download page for 0.6.2

- content/player/downloads.html
This needs some extra work for liblcf now because nobody works on boring website tasks (#4).
> Update Player download page for 0.6.2.1

- content/player/downloads.html
> macOS: Link to App bundle

- content/contribute/testers.html
- content/player/downloads.html
- content/tools/downloads.html
- nanoc.yaml
Not JS related but I like this clip: https://twitter.com/EmmanuelCAdigwe/status/1272510944162308097 :D
> Release 0.6.2.2

- content/404.html
- content/contact.html
- content/contact/irc.html
- layouts/default.html
- nanoc.yaml
This adds a new link "Contact" at the top right and a new page with all our contact information.
Also added a "Chat not workign" link to the IRC chat because Firefox does not like to load the iframe sometimes. (but works in Chrome)
> Add contact information

- README.md
- content/contact.html
- content/contact/irc.html
- content/contribute/testers.html
> Freenode is dead, long live Libera Chat!

- content/contact.html
- content/player/downloads.html
- content/player/guide/game_translation.md
- content/player/progress.html
> Release 0.7.0

- content/privacy/index.md
- layouts/default.slim
- nanoc.yaml
Lots of boring crap.
Website part is missing. Rest must be refined...
> Add privacy policy

- content/contact/index.md
privacy policy will be updated on another day
> Add link to fediverse

- content/player/progress.md
If more things should be moved/added, feel free to ask.
> Move External font support and Game controller/Joystick support on the progress page of the Player to done

- content/contact/index.md
Thanks Calisto for noticing this!
> Fix openrtp matrix channel link

- content/player/downloads.html
Getting an error that kiwiiirc is down while validating. Just loads extremely slow, maybe bad Telekom peering at home...
> Add WiiU download and document RTP paths

- content/player/downloads.html
Set the release date to Monday, should be feasible >.>
> Release Player 0.8.1 "Stun"

- content/contact/index.md
- content/player/downloads.html
also adds the BlueSky Link and replaces the FediVerse instance with a new one (bridge of BlueSky)
> Release Player 0.8.1.1 "Stun - Patch 1"
